"""HTML exporter — produces a self-contained HTML document with bionic styling baked in."""
from __future__ import annotations

from ..models import BionicSettings, DocumentModel
from ..transformer import transform_text_html


def export(doc: DocumentModel, settings: BionicSettings, title: str | None = None) -> tuple[bytes, str, str]:
    body_parts: list[str] = []
    open_list: str | None = None  # "ul" or "ol" or None
    for block in doc.blocks:
        if block.type == "list_item":
            tag = "ol" if block.ordered else "ul"
            if open_list != tag:
                if open_list:
                    body_parts.append(f"</{open_list}>")
                body_parts.append(f"<{tag}>")
                open_list = tag
        else:
            if open_list:
                body_parts.append(f"</{open_list}>")
                open_list = None

        rendered = transform_text_html(block.text or "", settings)
        if block.type == "heading":
            level = max(1, min(block.level or 2, 6))
            body_parts.append(f"<h{level}>{rendered}</h{level}>")
        elif block.type == "paragraph":
            body_parts.append(f"<p>{rendered}</p>")
        elif block.type == "list_item":
            body_parts.append(f"<li>{rendered}</li>")
        elif block.type == "blockquote":
            body_parts.append(f"<blockquote>{rendered}</blockquote>")
        elif block.type == "code":
            body_parts.append(f"<pre><code>{rendered}</code></pre>")
        elif block.type == "table_row":
            body_parts.append(f"<p class=\"row\">{rendered}</p>")
        elif block.type == "spacer":
            body_parts.append("<div class=\"spacer\"></div>")
    if open_list:
        body_parts.append(f"</{open_list}>")

    safe_title = (title or doc.filename or "Document").strip()
    html = _TEMPLATE.format(title=_escape(safe_title), body="\n".join(body_parts))
    return html.encode("utf-8"), "text/html", _safe_filename(doc.filename, ".html")


def _escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _safe_filename(name: str, new_ext: str) -> str:
    from pathlib import Path

    stem = Path(name).stem or "document"
    return f"{stem}.bionic{new_ext}"


_TEMPLATE = """<!doctype html>
<html lang="auto">
<head>
<meta charset="utf-8" />
<title>{title}</title>
<meta name="generator" content="Bionic Reader Pro" />
<style>
  :root {{
    color-scheme: light dark;
  }}
  html, body {{ margin: 0; padding: 0; }}
  body {{
    font-family: 'Lexend', 'Inter', system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
    line-height: 1.7;
    font-size: 18px;
    max-width: 70ch;
    margin: 2.5rem auto;
    padding: 0 1.25rem;
    color: #1a1a1a;
    background: #fbfaf6;
  }}
  h1, h2, h3, h4, h5, h6 {{ line-height: 1.25; margin-top: 1.5em; }}
  p, li, blockquote {{ margin: 0 0 1em; }}
  blockquote {{ border-left: 4px solid #c9c2a9; padding-left: 1em; color: #444; }}
  pre {{ background: #f1ecdb; padding: 1em; border-radius: 6px; overflow: auto; }}
  ul, ol {{ padding-left: 1.5em; }}
  .spacer {{ height: 1em; }}
  b.br-prefix {{ font-weight: 700; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #15161a; color: #ececec; }}
    blockquote {{ border-left-color: #555; color: #cdcdcd; }}
    pre {{ background: #1f2026; }}
  }}
</style>
</head>
<body>
{body}
<hr style="margin-top:3rem;opacity:.3" />
<p style="opacity:.6;font-size:.85em">Generated by Bionic Reader Pro — bionic prefix applied without altering the original file.</p>
</body>
</html>
"""
